### ISSUE TITLE
profile-movie-list-component

### ISSUE THREAD

**Issue by mehrb98** [Maxiboy441/PixelPrime#23]
Display movies list (see frontend images)

![Image](https://github.com/Maxiboy441/PixelPrime/assets/69319108/fbc8ecc8-0e0f-4ad5-ac9c-48a288687d42)

**Comment by Maxiboy441** [comment]
@mehrb98 what is the state of this ticket? Please reevaluate when it will be finished and put a new estimated enddate in the ticket

**Comment by Maxiboy441** [comment]
@mehrb98 i removed you from this cause it blocks others and your bussy with the other feature, I assigned @feliperamoss instead
