### ISSUE TITLE
UserManagement

### ISSUE THREAD

**Issue by Maxiboy441** [Maxiboy441/PixelPrime#27]
Please implement the whole logic for CRUD of a user, as well es the login,signup and signout logic. So the only thing not included is the view, the rest should be part of this ticket.
@mehrb98 mentioned it was made by the Identity package, figure out how or if you have todo it.

**Comment by Maxiboy441** [comment]
@mehrb98 please estimate you time. Thx

**Comment by Maxiboy441** [comment]
@mehrb98 please plan the tasks which are related with that, write them down and put a estimated enddate in the ticket.

**Comment by mehrb98** [comment]
@Maxiboy441  I didn't feel well, so I couldn't do it. I'm currently working on it

**Comment by Maxiboy441** [comment]
@mehrb98 ok, no problem. Wellbeeing goes first. If you feel you need support or that you cant handle that task, feels free to contact @feliperamoss or me.

Thx,
Maximilian Huber

**Comment by Maxiboy441** [comment]
> [@mehrb98](https://github.com/mehrb98) please estimate you time. Thx

!

**Comment by mehrb98** [comment]
@Maxiboy441 as discussed, I still have to deal with database and then I can be sure and commit.

**Comment by Maxiboy441** [comment]
@mehrb98 Thx for the estimation 👍 

Im exited for the review :)

**Comment by Maxiboy441** [comment]
@mehrb98 perfect. Ill start the review asap

**Comment by Maxiboy441** [comment]
Hey @mehrb98 ,
I did a first review and added the comments in the PR. Please adjust accordingly:


Thx :)

**Comment by Maxiboy441** [comment]
Check https://github.com/Maxiboy441/PixelPrime/pull/39 and open a new PR when you ready. Dont forget to merge develop in to your feature, @feliperamoss allready did some thing that fix stuff of you, and resolve conflicts. Thx

**Comment by Maxiboy441** [comment]
Sadly, we have to many issues with the package and the docker setup, so we have to figure out a diffrent way of doing that
